export {default as HomeGoods} from './HomeGoods'
export {default as ShowGoods} from './ShowGoods'
export {default as SearchGoods} from './SearchGoods'
export {default as InsertTypeGoods} from './InsertTypeGoods'
export {default as ShowGoodMainDetails} from './ShowGoodMainDetails'
export {default as ShowGoodDetails} from './ShowGoodDetails'
export {default as InsertGoods }from './InsertGoods'
