import {StyleSheet} from 'react-native';
const styles = StyleSheet.create({
  container: {
    flex: 1,
  },
  filter: {
    marginHorizontal: 20,
    marginVertical: 5,
    height: 60,
    backgroundColor: '#fff',
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 10,
    justifyContent: 'space-between',
  },
  textInput: {
    marginHorizontal: 10,
    marginVertical: 5,
    backgroundColor: '#C0E7C0',
    paddingHorizontal: 10,
    fontSize: 20,
    borderRadius: 10,
  },
  content: {
    marginHorizontal: 10,
    backgroundColor: 'gray',
    minHeight: 100,
    borderRadius: 10,
    padding: 10,
  },
  billUser: {
    marginHorizontal: 10,
    minHeight: 200,

    borderRadius: 10,

    marginBottom: 100,
  },
  containerItem: {
    marginHorizontal: 20,
    marginVertical: 8,
    minHeight: 60,
    borderWidth: 0.5,
    padding: 10,
    backgroundColor: '#fff',
    borderRadius: 10,
  },
  rowName: {
    flexDirection: 'row',
    marginVertical: 8,
    borderBottomWidth: 0.2,
    borderTopWidth: 0.2,
    minHeight: 40,
    alignItems: 'center',
  },
  ///
  viewImg: {
    marginVertical: 10,
    marginHorizontal: 10,
    backgroundColor: '#fff',
  },
  viewInfo: {
    marginHorizontal: 10,
    backgroundColor: '#fff',
    padding: 10,
    marginVertical: 10,
  },
  viewSize: {
    //marginHorizontal: 10,
    padding: 10,
    //flexDirection: 'row',
  },
  viewItemSize: {
    flexDirection: 'row',
    marginVertical: 5,
    minHeight: 40,
    backgroundColor: '#fff',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingHorizontal: 10,
    paddingRight: 50,
  },
  viewFix: {
    marginHorizontal: 10,
    minHeight: 50,
    backgroundColor: '#fff',
    marginBottom: 100,
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingHorizontal: 20,
  },
  button: {
    width: 100,
    height: 30,
    justifyContent: 'center',
    alignItems: 'center',
    borderRadius: 5,
    backgroundColor: 'blue',
  },
  fontW: {
    fontSize: 20,
    fontWeight: 'bold',
  },
  fontA: {
    fontSize: 14,
  },
  viewMain: {
    marginVertical: 5,
    backgroundColor: '#FFF',
    borderWidth: 0.5,
    borderColor: '#CFCFCF',
    borderRadius: 5,
    minHeight: 130,
    flexDirection: 'row',
    padding: 5,
    justifyContent: 'space-between',
  },
  image: {width: 100, height: 130, resizeMode: 'contain'},
  chose: {
    width: 80,
    height: 20,
    backgroundColor: '#0077FF',
    borderRadius: 5,
    justifyContent: 'center',
    alignItems: 'center',
    marginHorizontal: 5,
    marginVertical: 3,
  },
  font: {fontSize: 15, color: '#000', fontWeight: 'normal'},
  fontWeight: {fontSize: 15, color: '#000', fontWeight: 'bold'},
  pickerGender: {
    marginHorizontal: 100,
    minHeight: 40,
    backgroundColor: 'green',
    justifyContent: 'center',
    borderRadius: 5,
  },
  buttonFilter: {
    backgroundColor: 'green',
    width: 120,
    height: 40,
    justifyContent: 'center',
    borderRadius: 5,
  },
});

export default styles;
