export const data_home=[
    {
      id: 1,
      name: 'Quản lý nhân viên',
      icon: 'person-add-outline',
      background: '#F388D7',
      colorText: '#fff',
      navigation: 'Staff',
      permision: 'NaviStaff',
    },
    {
      id: 2,
      name: 'Quản lý khách hàng',
      icon: 'people-outline',
      background: '#FFA600',
      colorText: '#fff',
      navigation: 'HomeCustomer',
      permision: 'NaviCustomer',
    },
    {
      id: 3,
      name: 'Quản lý đơn hàng',
      icon: 'bar-chart-outline',
      background: '#00B7FF',
      colorText: '#fff',
      navigation: 'HomeOrder',
      permision: 'NaviOrder',
    },
    {
      id: 4,
      name: 'Quản lý mặt hàng',
      icon: 'apps-outline',
      background: 'pink',
      colorText: '#fff',
      navigation: 'HomeGoods',
      permision: 'NaviGoods',
    },
    {
      id: 4,
      name: 'Thống kê',
      icon: 'stats-chart-outline',
      background: 'pink',
      colorText: '#fff',
      navigation: 'Statistical',
      permision: 'NaviStatistical',
    },
    {
      id: 4,
      name: 'Quản lý phân quyền',
      icon: 'people-circle-outline',
      background: '#33B07E',
      colorText: '#fff',
      navigation: 'HomePermission',
      permision: 'NaviPremission',
    },
    {
      id: 5,
      name: 'Đăng bài',
      icon: 'newspaper-outline',
      background: '#33B07E',
      colorText: '#fff',
      navigation: 'HomePost',
      permision: 'NaviPremission',
    },
    {
      id: 6,
      name: 'Cài đặt thông tin',
      icon: 'cog-outline',
      background: '#B887E6',
      colorText: '#fff',
      navigation: 'HomePermission',
      permision: 'NaviPremission',
    },
  ];